name: Black

on: [push]

jobs:
  format:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12", "3.13"]
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black

      - name: Run Black (apply fixes)
        run: black $(git ls-files '*.py')

      - name: Save formatted changes
        run: |
          git add .
          git diff --cached --exit-code || echo "Changes detected"

      - name: Upload formatted files
        uses: actions/upload-artifact@v4
        with:
          name: formatted-code
          path: .

  commit:
    needs: format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Download formatted files
        uses: actions/download-artifact@v4
        with:
          name: formatted-code
          path: .

      - name: Commit and push if changed
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          if git diff --staged --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Apply Black formatting"
            git push
          fi
